import { styleVariants } from '@vanilla-extract/css';
export const THEMES = {
  theme: '#13D483',
  white: '#FFFFFF',
  default: '#303336',
  gray: '#808386',
  highlight: '#FA5A15',
  light_b1: '#F0F2F5',
  light_b2: '#E8E9EB',
};

export const COLORS = {
  blue: ' ',
  blue_background: ' ',
  brown: ' ',
  brown_background: ' ',
  default: THEMES.default,
  gray: THEMES.gray,
  gray_background: THEMES.light_b1,
  green: THEMES.theme,
  green_background: ' ',
  orange: THEMES.highlight,
  orange_background: ' ',
  pink: ' ',
  pink_background: ' ',
  purple: ' ',
  purple_background: ' ',
  red: ' ',
  red_background: ' ',
  yellow: ' ',
  yellow_background: ' ',
};

export const COLOR_STYLE_VARIANTS = styleVariants({
  default: { color: COLORS.default },
  blue: { color: COLORS.blue },
  blue_background: { backgroundColor: COLORS.blue_background },
  brown: { color: COLORS.brown },
  brown_background: { backgroundColor: COLORS.brown_background },
  gray: { color: COLORS.gray },
  gray_background: { backgroundColor: COLORS.gray_background },
  green: { color: COLORS.green },
  green_background: { backgroundColor: COLORS.gray_background },
  orange: { color: COLORS.orange },
  orange_background: { backgroundColor: COLORS.orange_background },
  pink: { color: COLORS.pink },
  pink_background: { backgroundColor: COLORS.pink_background },
  purple: { color: COLORS.purple },
  purple_background: { backgroundColor: COLORS.purple_background },
  red: { color: COLORS.red },
  red_background: { backgroundColor: COLORS.red_background },
  yellow: { color: COLORS.yellow },
  yellow_background: { backgroundColor: COLORS.yellow_background },
});
