import { createGlobalTheme, createGlobalThemeContract } from '@vanilla-extract/css';

export const vars = createGlobalThemeContract({
  color: {
    theme: 'color-theme',
    white: 'color-white',
    whitegray: 'color-whitegray',
    lightgray: 'color-lightgray',
    default: 'color-default',
    blueblack: 'color-blueblack',
    gray: 'color-gray',
    highlight: 'color-highlight',
    b1: 'color-light-b1',
    b2: 'color-light-b2',
    b3: 'color-light-b3',
  },
  notion: {
    blue: 'notion-blue',
    blue_background: 'notion-blue-background',
    brown: 'notion-brown',
    brown_background: 'notion-brown-background',
    default: 'notion-default',
    gray: 'notion-gray',
    gray_background: 'notion-gray-background',
    green: 'notion-green',
    green_background: 'notion-green-background',
    orange: 'notion-orange',
    orange_background: 'notion-orange-background',
    pink: 'notion-pink',
    pink_background: 'notion-pink-background',
    purple: 'notion-purple',
    purple_background: 'notion-purple-background',
    red: 'notion-red',
    red_background: 'notion-red-background',
    yellow: 'notion-yellow',
    yellow_background: 'notion-yellow-background',
  },
});

createGlobalTheme('[data-theme="light"]', vars, {
  color: {
    theme: '#F0F2F6',
    white: '#FFFFFF',
    whitegray: '#F5F6F7',
    lightgray: '#A0A2A6',
    default: '#303236',
    blueblack: '#404246',
    gray: '#808286',
    highlight: '#2578BE',
    b1: '#FFFFFF',
    b2: '#F2F2F3',
    b3: '#E6E6E7',
  },
  notion: {
    blue: '#1b64da',
    blue_background: '#90c2ff',
    brown: '#8a775f',
    brown_background: '#dbd3c8',
    default: '#303236',
    gray: '#808286',
    gray_background: '#E6E6E7',
    green: '#13D483',
    green_background: '#E4FA98',
    orange: '#FA5A15',
    orange_background: '#2578BE',
    pink: '#ff6666',
    pink_background: '#ffcccc',
    purple: '#7F38EC',
    purple_background: '#DA98FA',
    red: '#e42939',
    red_background: '#feafb4',
    yellow: '#ffb331',
    yellow_background: '#ffe69b',
  },
});

createGlobalTheme('[data-theme="dark"]', vars, {
  color: {
    theme: '#101216',
    white: '#FFFFFF',
    whitegray: '#F5F6F7',
    lightgray: '#A0A2A6',
    default: '#F7F7F7',
    blueblack: '#404246',
    gray: '#C0C3C6',
    highlight: '#2578BE',
    b1: '#202226',
    b2: '#303236',
    b3: '#404246',
  },
  notion: {
    blue: '#1b64da',
    blue_background: '#90c2ff',
    brown: '#8a775f',
    brown_background: '#dbd3c8',
    default: '#F7F7F7',
    gray: '#C0C3C6',
    gray_background: '#E6E6E7',
    green: '#13D483',
    green_background: '#E4FA98',
    orange: '#FA5A15',
    orange_background: '#2578BE',
    pink: '#ff6666',
    pink_background: '#ffcccc',
    purple: '#7F38EC',
    purple_background: '#DA98FA',
    red: '#e42939',
    red_background: '#feafb4',
    yellow: '#ffb331',
    yellow_background: '#ffe69b',
  },
});
